# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a1 = np.random.random((3,3,3))*10
a1

array([[[6.52719422, 3.08064463, 9.63896006],
        [5.59906068, 4.20800495, 6.62199379],
        [7.92043449, 4.31670547, 7.73530246]],

       [[4.7583807 , 3.77711511, 0.97457895],
        [1.40092543, 3.50142371, 1.96257962],
        [0.7508674 , 2.41189257, 0.04366704]],

       [[7.34476205, 3.45795376, 6.13081014],
        [4.03753192, 6.36518096, 1.32047464],
        [6.81747269, 2.29788966, 0.55567095]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
a2 = np.array([[0,0,0,0,0],[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0,],[0,0,0,4,0]])
a2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1:8:2,:8:2] = 1
x[:8:2,1:8:2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
a3 = np.floor(np.random.random((5,5))*10)
a3

array([[5., 2., 0., 5., 4.],
       [2., 4., 9., 8., 1.],
       [1., 4., 6., 1., 7.],
       [5., 5., 9., 0., 9.],
       [2., 6., 6., 1., 3.]])

# 5.  How to find common values between two arrays?

In [6]:
x1 =np.array([1,4,5,3,2,6])
x2 =np.array([4,6,7,3,2,8])

x3 =np.intersect1d(x1,x2)
x3

array([2, 3, 4, 6])

# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [18]:
# print(np.ndarray.all(x1))

print(x1 == x2)

[False False False  True  True False]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [22]:
vec = np.random.random(10)
print(vec)
vec[vec.argmax()]=0

print("\n\n",vec)

[0.41122709 0.54236793 0.15629354 0.28924569 0.5993558  0.05169258
 0.46089654 0.18334661 0.50813298 0.15706347]


 [0.41122709 0.54236793 0.15629354 0.28924569 0.         0.05169258
 0.46089654 0.18334661 0.50813298 0.15706347]


# 9. How to print all the values of an array?

In [26]:
ar1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,3,44,55,66]])
print(ar1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11  3 44 55 66]]


# 10.Subtract the mean of each row of a matrix

In [27]:
ar2 = ar1 - ar1.mean(axis=1, keepdims=True)
ar2

array([[ -2. ,  -1. ,   0. ,   1. ,   2. ],
       [ -2. ,  -1. ,   0. ,   1. ,   2. ],
       [-24.8, -32.8,   8.2,  19.2,  30.2]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [33]:
x3 = np.diag(a2.dot(a3))
x3

array([ 0.,  2., 18.,  3., 36.])

# 13.How to find the most frequent value in an array?

In [39]:
x = np.random.randint(0, 10, 10)
print(x)
print(np.bincount(x).argmax())
n=1

[0 8 8 7 0 6 2 9 7 6]
0


# 14.How to get the n largest values of an array

In [40]:
print (x[np.argsort(x)[-n:]])

[9]


# 15.How to create a record array from a regular array?

In [42]:
a1=np.array([101,102,103,104])
a2=np.array(['OMKAR','GANESH','VINOD','ANIL'])
a3=np.array([80,76,66,79])
result= np.core.records.fromarrays([a1, a2, a3],names='Roll no.,Name,Marks')
print(result[0])
print(result[1])
print(result[2])

(101, 'OMKAR', 80)
(102, 'GANESH', 76)
(103, 'VINOD', 66)
